#!/usr/bin/env bash
#installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "web-01" when queried
#++    at the root with a curl GET req

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create index.html with "web-01"
echo "web-01" | sudo tee /etc/nginx/html/index.html

# Configure Nginx to listen on port 80 and return "Hello World!"
cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location / {
        add_header Content-Type text/html;
        return 200 "Hello World!\n";
    }
}
EOL

# Restart Nginx
service nginx restart

