#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo"Nginx installed and configured. Access http://localhost/ to see 'Hello World!'"
service nginx restart
