#!/usr/bin/env bash

# Install and configure Nginx
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html

# Configure Nginx for redirection
REDIRECT_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
        return 301 https://sketchfab.com/bluepeno/models;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}"

# Write the redirection configuration to the default Nginx site
echo -e "$REDIRECT_CONFIG" | tee /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
