#!/usr/bin/env bash
# Install Nginx and create necessary directories and files
apt-get update
apt-get install -y nginx
mkdir -p /var/www/html
echo "web-01" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx for custom 404 page
NGINX_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Write the Nginx configuration to the default site
echo -e "$NGINX_CONFIG" | tee /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
