#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Create a custom HTML page
echo 'Hello world' > /var/www/html/index.nginx-debian.html

# Configure Nginx to include custom header X-Served-By for web-01
sed -i "/listen 80;/a \        add_header X-Served-By 226177-web-01;" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

