#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response
apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo 'Hello world' > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 226177-web-01;/a add_header X-Served-By \$226177-web-01;" /etc/nginx/sites-available/default
service nginx restart
