#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containing its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#     "Usage: manage_my_process {start|stop|restart}"

FILE="/var/run/my_process.pid"

create_pid_file()
{
    echo $$ | sudo tee "$FILE" > /dev/null
}

start_manage_my_process()
{
    create_pid_file
    ./manage_my_process &
    echo "manage_my_process started"
}

stop_manage_my_process()
{
    if [ -e "$FILE" ]; then
        sudo pkill -F "$FILE"
        sudo rm "$FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

if [ "$1" == "start" ]; then
    start_manage_my_process

elif [ "$1" == "stop" ]; then
    stop_manage_my_process

elif [ "$1" == "restart" ]; then
    stop_manage_my_process
    start_manage_my_process
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
