#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"


FILE="/var/run/my_process.pid"

create()
{
    sudo touch $FILE
    sudo echo $$ > $FILE
}

if [ "$1" == "start" ]; then
    create
    ./manage_my_process &
    echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
    if [ -e "$FILE" ]; then
        sudo pkill -f "./manage_my_process"
        sudo rm "$FILE"
    else
        echo "manage_my_process is not running."
    fi
    echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then
    $0 stop >& /dev/null
    $0 start >& /dev/null
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
